// AI 识别 schema 的事实源在 shared；前端服务层只做 re-export，避免 Worker/Go 响应契约分叉。
export {
  AI_RECOGNITION_MAX_IMAGES,
  AI_RECOGNITION_MAX_IMAGE_BYTES,
  AI_RECOGNITION_MAX_SUBSCRIPTIONS,
  AI_RECOGNITION_MAX_TEXT_CHARS,
  aiRecognizedSubscriptionDraftSchema,
  aiModelListErrorDetailsSchema,
  aiModelListItemSchema,
  aiModelListRequestSchema,
  aiModelListResponseSchema,
  aiRecognitionDiagnosticsSchema,
  aiRecognitionErrorDetailsSchema,
  aiRecognitionModelInputModeSchema,
  aiRecognitionProviderSchema,
  aiRecognitionSettingsSchema,
  aiRecognitionTestRequestSchema,
  aiRecognitionTestResponseSchema,
  aiRecognizeResponseSchema,
  aiThinkingControlSchema,
  anthropicThinkingControlSchema,
  anthropicThinkingEffortSchema,
  geminiThinkingControlSchema,
  geminiThinkingLevelSchema,
  openaiReasoningEffortSchema,
  openaiThinkingControlSchema,
} from "@renewlet/shared/schemas/ai-recognition";

export type {
  AiRecognizedSubscriptionDraft,
  AiModelCapability,
  AiModelListErrorDetails,
  AiModelListItem,
  AiModelListRequest,
  AiModelListResponse,
  AiRecognitionDiagnostics,
  AiRecognitionErrorDetails,
  AiRecognitionModelInputMode,
  AiRecognitionProvider,
  AiRecognitionSettings,
  AiRecognitionTestRequest,
  AiRecognitionTestResponse,
  AiRecognizeResponse,
  AiThinkingControl,
} from "@renewlet/shared/schemas/ai-recognition";
