import type { ServerI18nKey } from "./server-i18n-catalog";

// Code generated by scripts/generate-built-in-config-labels.mjs; DO NOT EDIT.
// 日历 Feed 公开路由不能访问前端 Lingui catalog；这里保存生成期对齐的服务端 i18n key。

const CALENDAR_FEED_BUILT_IN_CATEGORY_LABEL_KEYS = {
  "productivity": "category.productivity",
  "entertainment": "category.entertainment",
  "lifestyle": "category.lifestyle",
  "finance": "category.finance",
  "streaming": "category.streaming",
  "music": "category.music",
  "gaming": "category.gaming",
  "utilities": "category.utilities",
  "cloud_storage": "category.cloudStorage",
  "education": "category.education",
  "health_fitness": "category.healthFitness",
  "food_dining": "category.foodDining",
  "shopping": "category.shopping",
  "travel": "category.travel",
  "business": "category.business",
  "communication": "category.communication",
  "developer_tools": "category.developerTools",
  "design": "category.design",
  "ai_tools": "category.aiTools",
  "security_vpn": "category.securityVpn",
  "hosting_domains": "category.hostingDomains",
  "news_media": "category.newsMedia",
  "other": "category.other",
} as const satisfies Record<string, ServerI18nKey>;

const CALENDAR_FEED_BUILT_IN_PAYMENT_METHOD_LABEL_KEYS = {
  "alipay": "payment.alipay",
  "wechat": "payment.wechat",
  "credit_card": "payment.creditCard",
  "debit_card": "payment.debitCard",
  "paypal": "payment.paypal",
  "apple_pay": "payment.applePay",
  "google_pay": "payment.googlePay",
  "bank_transfer": "payment.bankTransfer",
  "crypto": "payment.crypto",
  "direct_debit": "payment.directDebit",
  "money": "payment.money",
  "samsung_pay": "payment.samsungPay",
  "klarna": "payment.klarna",
  "amazon_pay": "payment.amazonPay",
  "sepa": "payment.sepa",
  "skrill": "payment.skrill",
  "sofort": "payment.sofort",
  "stripe": "payment.stripe",
  "affirm": "payment.affirm",
  "elo": "payment.elo",
  "facebook_pay": "payment.facebookPay",
  "giropay": "payment.giropay",
  "ideal": "payment.ideal",
  "union_pay": "payment.unionPay",
  "interac": "payment.interac",
  "paysafe": "payment.paysafe",
  "poli": "payment.poli",
  "qiwi": "payment.qiwi",
  "shop_pay": "payment.shopPay",
  "venmo": "payment.venmo",
  "verifone": "payment.verifone",
  "webmoney": "payment.webmoney",
  "other": "payment.other",
} as const satisfies Record<string, ServerI18nKey>;

function hasOwnKey<T extends object>(source: T, key: string): key is Extract<keyof T, string> {
  return Object.prototype.hasOwnProperty.call(source, key);
}

export function calendarFeedBuiltInCategoryLabelKey(value: string): ServerI18nKey | undefined {
  return hasOwnKey(CALENDAR_FEED_BUILT_IN_CATEGORY_LABEL_KEYS, value)
    ? CALENDAR_FEED_BUILT_IN_CATEGORY_LABEL_KEYS[value]
    : undefined;
}

export function calendarFeedBuiltInPaymentMethodLabelKey(value: string): ServerI18nKey | undefined {
  return hasOwnKey(CALENDAR_FEED_BUILT_IN_PAYMENT_METHOD_LABEL_KEYS, value)
    ? CALENDAR_FEED_BUILT_IN_PAYMENT_METHOD_LABEL_KEYS[value]
    : undefined;
}
