// 媒体候选和上传响应同时服务 Logo/Icon 选择器、Go resolver 与 Worker R2 路径，必须从 shared 保持同一运行时 schema。
export {
  mediaCandidateConfidenceSchema,
  mediaCandidateGroupSchema,
  mediaCandidateKindSchema,
  mediaCandidateModeSchema,
  mediaCandidateResolveItemResponseSchema,
  mediaCandidateResolveItemSchema,
  mediaCandidateResolveRequestSchema,
  mediaCandidateResolveResponseSchema,
  mediaCandidateResolvePayloadSchema,
  mediaCandidateSchema,
  mediaCandidateSourceSchema,
  assetInUseDetailsSchema,
  uploadImageResponseSchema,
  uploadImagePayloadSchema,
  uploadKindSchema,
  uploadedAssetSchema,
  uploadedAssetsPageSchema,
  uploadedAssetsPageResponseSchema,
  builtInIconIndexStatusResponseSchema,
  builtInIconIndexProviderCheckResponseSchema,
  builtInIconIndexProviderCheckPayloadSchema,
  builtInIconIndexProviderCountsSchema,
  builtInIconIndexProviderRefreshResponseSchema,
  builtInIconIndexProviderRefreshPayloadSchema,
  builtInIconIndexProviderStatusSchema,
  builtInIconSeedMetadataSchema,
  builtInIconIndexSourceSchema,
  builtInIconIndexStatusSchema,
  builtInIconProviderVersionSchema,
} from "@renewlet/shared/schemas/media";

export type {
  BuiltInIconIndexProviderCheckResponse,
  BuiltInIconIndexProviderCounts,
  BuiltInIconIndexProviderRefreshResponse,
  BuiltInIconIndexProviderStatus,
  BuiltInIconSeedMetadata,
  BuiltInIconIndexSource,
  BuiltInIconIndexStatus,
  BuiltInIconProviderVersion,
  ApiUploadImageResponse,
  AssetInUseDetails,
  MediaCandidate,
  MediaCandidateConfidence,
  MediaCandidateGroup,
  MediaCandidateKind,
  MediaCandidateMode,
  MediaCandidateResolveItem,
  MediaCandidateResolveItemResponse,
  MediaCandidateResolveRequest,
  MediaCandidateResolveResponse,
  MediaCandidateSource,
  UploadKind,
  UploadedAsset,
  UploadedAssetsPage,
} from "@renewlet/shared/schemas/media";
